spring.application.name=ingredient-srp
spring.datasource.url=jdbc:postgresql://localhost:5432/mini_dish_db
spring.datasource.username=postgres
spring.datasource.password=angela
spring.datasource.driver-class-name=org.postgresql.Driver